### ISSUE TITLE
ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/matlab-ci#43]
```
  ci:auth Authentication complete +107ms
Error: X-Github-Event is not acceptable
node:events:353
      throw er; // Unhandled 'error' event
      ^
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:278:15)
    at ServerResponse.end (node:_http_outgoing:819:15)
    at /home/ibladmin/Documents/CI/matlab-ci/serve.js:101:32
    at hasError (/home/ibladmin/Documents/CI/matlab-ci/node_modules/github-webhook-handler/github-webhook-handler.js:89:7)
    at handler (/home/ibladmin/Documents/CI/matlab-ci/node_modules/github-webhook-handler/github-webhook-handler.js:109:14)
    at /home/ibladmin/Documents/CI/matlab-ci/serve.js:101:4
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
Emitted 'error' event on ServerResponse instance at:
    at emitErrorNt (node:_http_outgoing:695:9)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

**Comment by k1o0** [comment]
Seems to be caused by GitHub app options.  An event that isn't 'push' or 'pull_request' was sent, the github-webhook-handler rejects it but the `srv.post` callback doesn't catch the emitted error.
